---
title: "GIS 1887"
author: "Ye Seul Byeon"
date: "5/16/2018"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(rgdal)
library(sp)
library(ggmap)
library(readxl)
library(knitr)
library(viridis)
library(ggthemes)
library(plotly)
knitr::opts_chunk$set(echo = TRUE)


theme_set(theme_map())
```

```{r import-tabular}
#reading in excel file
#list.files('data')
tabular <- read_xlsx('data/JapanG_RawData_beta.xlsx')
tabular
#tidying the tabular dataset
tabular_tidy <- tabular %>%
  #converting meiji year to calendar year
  mutate(MeijiYear = as.numeric(gsub("M", "", MeijiYear))) %>%
  mutate(Year = MeijiYear + 1867) %>%
  select(KGun_ID, Kuni_ID, Ken_Nm, Kuni_Nm, Gun_Nm, Year, G063, G064, G121, G203, G206)

#rename columns
names(tabular_tidy)[7:11] = c("All_Bovine", "All_Horses", "Malnutrition_Deaths", "Bovine_Bred", "Horses_Bred")
```

```{r animal-consumption-clean, eval = FALSE}
animal_products <- read_xlsx('data/animal_products_japan.xlsx')


ggplot(data = animal_products, aes(x = Year, y = Raw_Milk))+
  geom_bar(stat = "identity") +
  theme_tufte() +
  labs(
    title = "Production of Raw Milk in Japan, 1894-2003",
    y = "Raw Milk Production (in tons)",
    x = "Year"
  )


#p <- plot_ly(animal_products, x = ~Year, y = ~Raw_Milk, type = 'bar',
#             marker = list(color = 'rgb(158,202,225)',
#                      line = list(color = 'rgb(8,48,107)',
#                                  width = 1.5))) %>%
#  layout(title = "January 2013 Sales Report",
#         xaxis = list(title = ""),
#         yaxis = list(title = ""))


```



```{r read-shp}
list.files("data")
japan1887_kuni <- readOGR("./data/JapanKuni_1887.shp")
hokkaido1887_kuni <- readOGR("./data/JapanKuni_Hokkaido__1887.shp")
japan1887_gun <- readOGR("./data/JapanGun_1887.shp")
japan1887_ken <- readOGR("./data/JapanKen_1887.shp")
japan_cities <- readOGR("./data/JapanT_20130319.shp")
joined <- readOGR("./data/new_shp.shp")
```
```{r process-shp}
#hokkaido kuni
hokkaido1887_process <- hokkaido1887_kuni %>%
  fortify(region = "KUNI_RM") %>%
  as_tibble() %>%
  left_join(hokkaido1887_kuni@data, by = c("id" = "KUNI_RM"))


#japan kuni
japan1887_kuni_process <- japan1887_kuni %>%
  fortify(region = "KUNI_RM") %>%
  as_tibble() %>%
  left_join(japan1887_kuni@data, by = c("id" = "KUNI_RM")) %>%
  mutate(Kuni_ID = OBJECTID)


names(japan1887_kuni_process)[6]<-"Kuni_Nm"
japan1887_kuni_process <- japan1887_kuni_process %>%
  mutate(id = Kuni_ID)


#japan gun
japan1887_gun_process <- japan1887_gun %>%
  fortify(region = "GUN_RM") %>%
  as_tibble() %>%
  left_join(japan1887_gun@data, by = c("id" = "GUN_RM"))

#japan ken
japan1887_ken_process <- japan1887_ken %>%
  fortify(region = "KEN_RM") %>%
  as_tibble() %>%
  left_join(japan1887_ken@data, by = c("id" = "KEN_RM"))

head(japan1887_kuni)
#QGIS joined shp file
new_shp <- joined %>%
  fortify(region = "KUNI_RM") %>%
  as_tibble() %>%
  left_join(joined@data, by = c("id" = "KUNI_RM"))

new_shp <- new_shp %>%
  select(long, lat, id, OBJECTID, JapanG_R99.9, JapanG_R99.10, JapanG_R99.34, JapanG_R99.73, JapanG_R99.74)

```



```{r loading-basemaps, eval = FALSE}
hokkaido <- ggplot(data = hokkaido1887_process, mapping = aes(x = long, y = lat, group = group)) + 
  coord_fixed(1.3) + 
  geom_polygon(color = "#252525", fill = "#a6bddb", size = 0.2)


japan_kuni <- ggplot(data = japan1887_kuni_process, mapping = aes(x = long, y = lat, group = group)) + 
  coord_fixed(1.3) + 
  geom_polygon(color = "#252525", fill = "#a6bddb", size = 0.2)

ggplot(data = japan1887_ken_process, mapping = aes(x = long, y = lat, group = group)) + 
  coord_fixed(1.3) + 
  geom_polygon(color = "#252525", fill = "#a6bddb", size = 0.2) +
  geom_text(label = Ken_Nm)

japan1887_ken_process

japan_gun <- ggplot(data = japan1887_gun_process, mapping = aes(x = long, y = lat, group = group)) + 
  coord_fixed(1.3) + 
  geom_polygon(color = '#252525', fill = "#a6bddb", size = 0.2)

joined <- ggplot(data = joined, mapping = aes(x = long, y = lat, group = group)) + 
  coord_fixed(1.3) + 
  geom_polygon(color = "#252525", fill = "#a6bddb", size = 0.2)

```

```{r}
sum_tabular_cows <- tabular_tidy %>%
  group_by(Kuni_ID, Kuni_Nm) %>%
  summarize(cows_count = sum(All_Bovine, na.rm = TRUE))

sum_tabular_horses <- tabular_tidy %>%
  group_by(Kuni_ID, Kuni_Nm) %>%
  summarize(horses_count = sum(All_Horses, na.rm = TRUE))


ggplot() + 
    ggtitle("No. of Cows, by Kuni") +
    geom_map(data = japan1887_kuni_process, map = japan1887_kuni_process, 
             aes(x = long, y = lat, map_id = Kuni_ID), fill = "#D3D3D3", color = "#F5F5F5", size = 0.15) +
    geom_map(data = sum_tabular_cows, map = japan1887_kuni_process, 
             aes(fill = cows_count, map_id = Kuni_ID), size=0.15) + 
  coord_fixed(x = japan1887_kuni_process$long, y = japan1887_kuni_process$lat) + 
  scale_fill_viridis()

ggplot() + 
    ggtitle("No. of Horses, by Kuni") +
    geom_map(data = japan1887_kuni_process, map = japan1887_kuni_process, 
             aes(x = long, y = lat, map_id = Kuni_ID),  fill = "#D3D3D3", color = "#F5F5F5", size = 0.15) +
    geom_map(data = sum_tabular_horses, map = japan1887_kuni_process, 
             aes(fill = horses_count, map_id = Kuni_ID), size=0.15) + 
    coord_fixed(x = japan1887_kuni_process$long, y = japan1887_kuni_process$lat) + 
    scale_fill_viridis()

```


